//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace capaDato
{
    using System;
    using System.Collections.Generic;
    
    public partial class employee1
    {
        public int id { get; set; }
        public string first_name { get; set; }
    }
}
